/**
 * Stable - Auth Service
 * An authentication service API for Stable
 *
 * The version of the OpenAPI document: 0.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RegisterRequestDto {
    /**
    * The email of the user
    */
    'email': string;
    /**
    * The password of the user
    */
    'password': string;
    /**
    * The given name of the user
    */
    'givenName': string;
    /**
    * The family name of the user
    */
    'familyName': string;
    /**
    * Gender query parameter
    */
    'gender'?: RegisterRequestDto.GenderEnum;
    /**
    * Acceptance of Terms and Privacy Policy
    */
    'acceptTerms': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        },
        {
            "name": "givenName",
            "baseName": "givenName",
            "type": "string"
        },
        {
            "name": "familyName",
            "baseName": "familyName",
            "type": "string"
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "RegisterRequestDto.GenderEnum"
        },
        {
            "name": "acceptTerms",
            "baseName": "acceptTerms",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return RegisterRequestDto.attributeTypeMap;
    }
}

export namespace RegisterRequestDto {
    export enum GenderEnum {
        Male = <any> 'male',
        Female = <any> 'female'
    }
}
